Finite State Machine
StudioTBA/CoronaIO pull request #17
Opened 2020-03-12 00:48 UTC by gnoriega27

## What issue is this PR solving?
Closes: #15 

## Description of change
Simple finite state machine with an example.

## How to reproduce the changes
1. Open the FSM scene.
2. Start.
3. Click anywhere in the plane.
4. While the player is moving you can press "spacebar" and it will run.
5. Observer the state changes in the textview.

## Screenshots or GIFs
If applicable, show off your work!

2020-03-12 18:19 UTC, mjimenez98 commented on Assets/Scripts/FSM/State.cs
> +        /// Callback when that is called when you enter the state.
```suggestion
        /// Callback that is called when you enter the state.
```

2020-03-12 18:20 UTC, mjimenez98 commented on Assets/Scripts/FSM/State.cs
> +        /// Callback when that is called when you exit the state.
```suggestion
        /// Callback that is called when you exit the state.
```

2020-03-12 18:21 UTC, mjimenez98 commented on Assets/Scripts/FSM/State.cs
> +        /// State machine where that this state belongs to.
```suggestion
        /// State machine to which this state belongs.
```

2020-03-12 18:30 UTC, mjimenez98 approved these changes
I am loving this, great work!

I made a few petty suggestions for clearer comments but other than that, this couldn't be better.

If you feel like writing about this architecture and how to use it in the README, please feel welcome to.

![giphy](https://user-images.githubusercontent.com/10281272/76555177-898aa880-646d-11ea-8018-84027148ec84.gif)

2020-03-12 18:33 UTC, mjimenez98 requested changes
I just noticed the .idea/ files. I can remove these. Putting the approval on hold until then.

2020-03-12 18:36 UTC, mjimenez98 approved these changes
We are good to go!

2020-03-12 20:40 UTC, ghost approved these changes
This sucks. Merge it.

2020-03-17 23:36 UTC, gnoriega27 commented
Todo:
- [ ] Add transition abstraction
- [ ] Add event listener abstraction

2020-03-18 19:29 UTC, mjimenez98 commented
Going over it again, I was trying to find problems with the code but couldn't find any. So that's great! 

My only question is, if the behavior in the scene _FSM_ is already being demonstrated in _HumanAgent_, could we delete the former so we have less things in the project?

2020-03-18 20:44 UTC, gnoriega27 commented
They are showing different examples. One is purely a FMS, while the other is the abstraction of an agent that has a FSM.

2020-03-18 21:15 UTC, merged