Zombie fsm
StudioTBA/CoronaIO pull request #65
Opened 2020-03-27 20:46 UTC by taramic42

## What issue is this PR solving?
Closes: https://github.com/StudioTBA/CoronaIO/issues/55

## Description of change
Files for Finite State machine were created and attached to the FlockCenter prefab to allow developement of more strategic Zombie AI. FlockCenter object no longer can go through objects as it now has a NavMeshAgent component attached.

## How to reproduce the changes
Open FlockCenter prefab
See the new components
Created files are located in Scripts/Agents/Zombie folder

2020-03-28 20:58 UTC, mjimenez98 submitted a review, later dismissed

2020-03-29 18:12 UTC, gnoriega27 commented
@taramic42 you purposely added only the "Idle state" right to the prefab right?

2020-03-29 18:15 UTC, gnoriega27 requested changes
Overall good job. Just wanted to know the "missing states" in the prefab since at the moment only idle is attached and then I'll approve.

2020-03-29 18:15 UTC, gnoriega27 commented on Assets/Scripts/Agent/Zombie/States/Attack.cs
> +        private DataHolder _dataHolder;
```suggestion
        private ZombieDataHolde _dataHolder;
```

2020-03-29 18:15 UTC, gnoriega27 commented on Assets/Scripts/Agent/Zombie/ZombieStateMachine.cs
> +        private DataHolder _dataHolder;
Make your own "data holder". Each agent should have it's own data holder since this is how the States share data.

2020-03-29 20:43 UTC, gnoriega27 commented
Also there seems to be a "bug", when the flock center is moved to a position with obstacles or a "corner", they zombies cannot seem to find a proper path and get stuck.

2020-04-08 15:06 UTC, gnoriega27 approved these changes
Done!

2020-04-08 15:07 UTC, merged